import React from 'react';
import { Dimensions, View, StyleSheet, Image } from 'react-native';
import { BlurView } from '@react-native-community/blur';

const { width, height } = Dimensions.get('screen');

const AccountCreatedPopUpScreen: React.FC = () => {
  return (
    <View style={styles.container}>
      <BlurView style={styles.absoluteBlur} blurType="materialLight" blurAmount={10} />
      <View style={styles.popViewContainer}>
        <Image source={require('../assets/images/Message.png')} style={styles.image} />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  absoluteBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  popViewContainer: {
    backgroundColor: 'white',
    width: 327,
    height: 298,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    width: 100, 
    height: 100, 
    resizeMode: 'contain',
  },
});

export default AccountCreatedPopUpScreen;
