import React from 'react';

export const constantString = {
  login: 'Login',
  email: 'Email',
  password: 'Password',
  newPassword: 'New Password',
  mobileNo: 'Mobile No',
  name: 'Name',
  confirmPassword: 'Confirm Password',
  loginError: 'Login Error',
  apiError: 'API Error:',
  enterValidEmail: 'Enter a valid email',
  confirmPasswordLength: 'Confirm Password must be at least 8 characters',
  confirmPasswordDoesnotMatch: "Confirm Password Doesn't match",
  mobileLength: 'Enter valid Mobile Number with at least 10 digits',
  passwordLength: 'Password must be at least 8 characters long',
  apiLoginResponse: 'API Login Response:',
  apiLoginError: 'API Login Error:',
  loginSuccessful: 'Login successful',
  invalidCredentials: 'Invalid credentials',
  errorResponse: 'Error Response:',
  success: 'success',
  sucessCaps: 'Success',
  loginFailed: 'Login Failed',
  error: 'error',
  errorCaps: 'Error',
  someThingWentWrong: 'Something went wrong. Please try again later',
  forgotPassword: 'Forgot Password?',
  signIn: 'Sign In',
  dontHaveAccount: "Don't have an account?",
  createAccount: 'Create an Account',
  unexpectedError: 'Unexpected error occurred.',
  emailRetrived: 'Email retrieved:',
  errorFetchingEmail: 'Error fetching email:',
  otpResendSent: 'OTP resend sent successfully!',
  otpResendFailed: 'OTP resend failed',
  otpResendError: 'API Resend OTP Error:',
  otpResendResponse: 'API Resend OTP Response:',
  resetEmailId: 'ResetEmailId',
  failed: 'Failed',
  reSendCode: 'Resend Code',
  continue: 'Continue',
  didNotReceiveTheCode: "Didn't receive the code?",
  otpText: 'Enter the verification code we just sent you on your email address',
  resetPassword: 'Reset Password',
  resetPasswordText:
    'Lost Your Password? Please enter your email will receive a link to create a new password via email.',
  apiResetError: 'API Reset Error',
  passwordSuccessfully: 'Password reset email sent successfully!',
  close: 'Close',
  loginNowThanks: 'Please Login now Thanks',
  yourAccountCreated: 'Your Account is Created',
  checkYourMail: 'Check your mail',
  recoverInstruction:
    'We have sent a password recover instructions to your email.',
  privacyPolicy: 'Privacy Policy',
  termsAndConditions: 'Terms & Conditions',
  submit: 'Submit',
  agreeText: 'I hereby agree to Terms and Conditions and Privacy Policy',
  aPICreateAccountError: 'API Create Account Error:',
  createAccountFailed: 'Create Account Failed',
  accountCreatedSuccessful: 'Account created successfully!',
  aPICreateAccountResponse: 'API Create Account Response:',
  createAnAccount: 'Create an Account',
  acceptTheTC: 'Please accept the Terms and Conditions',
  couldnotOpenUrl: 'Could not open URL',
  changePasswordText:
    'Your new password must be different from previously used passwords.',
  changePassword: 'Change Password',
  aPIChangePasswordResponse: 'API Change Password Response:',
  aPIChangePasswordError: 'API Change Password Error:',
  changePasswordFailed: 'Change Password Failed',
  invalidEmail: 'Invalid email',
  successfullyUpdated: 'Successfully Updated',
  yourProfileHasBeenUpdated: 'Your Profile has been updated',
  updateProfile: 'Update Profile',
  apiEditProfileResponse: 'API Edit Profile Response:',
  editProfileFailed: 'Edit Profile Failed',
  passwordChanged: 'Password Changed',
  profile: 'Profile',
  editProfile: 'Edit Profile',
  pushNotifications: 'Push Notifications',
  tellaFriend: 'Tell a Friend',
  logout: 'Logout',
  aboutUs: 'About Us',
  errorFetchingUserData: 'Error fetching user data:',
  emailEmpty: 'Email Cannot be empty',
  apiResetResponse: 'API Reset Response:',
  enterName: 'Enter Name',
  library: 'Library',
  feeds: 'Feeds',
};
