export const constantImage = {
  bgBackGround: require('../assets/images/BG.png'),
  tickSquare: require('../assets/images/TickSquare.png'),
  message: require('../assets/images/Message.png'),
  logo: require('../assets/images/logo.png'),
  password: require('../assets/images/Password.png'),
  pushNotification: require('../assets/images/Notification.png'),
  terms: require('../assets/images/Terms.png'),
  privacy: require('../assets/images/Privacy.png'),
  referFriends: require('../assets/images/ReferFriends.png'),
  aboutUs: require('../assets/images/AboutUs.png'),
  rightArrow: require('../assets/images/RightArrow.png'),
  setProfile: require('../assets/images/SetProfile.png'),
  logOut: require('../assets/images/Logout.png'),
  videoIcon: require('../assets/images/ic_video_icon.png'),
  audioIcon: require('../assets/images/ic_audio_icon.png'),
  docIcon: require('../assets/images/ic_doc.png'),
  techmangoLogo: require('../assets/images/TechmangoLogo.png'),
  libraryIcon: require('../assets/images/ic_Library.png'),
  feedIcon: require('../assets/images/Play.png'),
  profileIcon: require('../assets/images/Profile.png'),
  catAudioIcon: require('../assets/images/cat_audio.png'),
  catVideoIcon: require('../assets/images/cat_video.png'),
  playIcon: require('../assets/images/ic_play.png'),
  pauseIcon: require('../assets/images/ic_pause.png'),
  rewindIcon: require('../assets/images/ic_rewind.png'),
  forwardIcon: require('../assets/images/ic_forward.png'),
};